version: '3'

#NETWORK
networks:
  my-network:
    driver: bridge
#VOLUMES
volumes:
  dir-site:
    driver_opts:
      device: ./mycode/sites/
      o: bind
      type: none
services:
  #PHP
  my-php:
    container_name: php-product
    build:
      context: ./
      dockerfile: Dockerfile
    hostname: php
    restart: always
    networks:
      - my-network
    volumes:
      - dir-site:/home/sites/
    # #HTTPD
    # my-httpd:
    #   container_name: httpd-product
    #   image: "httpd:latest"
    #   hostname: httpd
    #   restart: always
    #   networks:
    #     - my-network
    #   volumes:
    #     - dir-site:/home/sites/
    #     - ./mycode/httpd.conf:/usr/local/apache2/conf/httpd.conf

    #   ports:
    #     - "8080:80"
    #     - "443:443"
    # #MYSQL
    # my-sql:
    #   container_name: mysql-product
    #   image: "mysql:latest"
    #   hostname: mysql
    #   restart: always
    #   networks:
    #     - my-network
    #   volumes:
    #     - ./mycode/db:/var/lib/mysql
    #     - ./mycode/my.cnf:/etc/mysql/my.cnf
    #   environment:
    #     - MYSQL_ROOT_PASSWORD=123abc
    #     - MYSQL_DATABASE=db_site
    #     - MYSQL_USER=siteuser
    #     - MYSQL_PASSWORD=sitepassword
